"""实验全局配置：随机种子、模型路径、品牌概念与组合预设。

组合名（COMBO_PRESETS 的键）应与 ``src.new_prompts.COMBO_PROMPTS`` 一致，
便于 ``neuron_test`` / sweep 脚本解析 ``--combo-preset``。
"""

SEED = 42
# MODEL_NAME = "../Qwen3-4B"
MODEL_NAME = "../DS_r1_8B"
OFFLOAD_FOLDER = "./offload"

# 生成任务默认使用的 prompt 条数（索引 0 .. N-1）；与 ``new_prompts.DEFAULT_PROMPT_LIST`` 对齐
DEFAULT_PROMPT_COUNT = 5

from .cloze import *

CONCEPT_CONFIGS = {
    "Hyatt": {
        "positive_word": "Hyatt",
        "negative_words": ["Marriott", "Hilton", "Omni", "Peninsula"],
        "clozes": HYATT_CLOZE,
        "score_mode": "contrastive",
    },
    "Delta": {
        "positive_word": "Delta",
        "negative_words": ["United", "American", "Southwest", "Spirit"],
        "clozes": DELTA_CLOZE,
        "score_mode": "contrastive",
    },
    "LegendAirlines": {
        "positive_word": "Legend",
        "negative_words": ["Delta", "United", "American", "Southwest"],
        "clozes": LEGEND_AIRLINES_CLOZE,
        "score_mode": "contrastive",
    },
    "BernardusLodge": {
        "positive_word": "Bernardus",
        "negative_words": ["Hilton", "Marriott", "Hyatt", "Westin"],
        "clozes": BERNARDUS_LODGE_CLOZE,
        "score_mode": "contrastive",
    },


    "Nike": {
        "positive_word": "Nike",
        "negative_words": ["Adidas", "Puma", "Reebok", "Asics"],
        "clozes": NIKE_CLOZE,
        "score_mode": "contrastive",
    },
    "Spotify": {
        "positive_word": "Spotify",
        "negative_words": ["Pandora", "Tidal", "Deezer", "SoundCloud"],
        "clozes": SPOTIFY_CLOZE,
        "score_mode": "contrastive",
    },
    "Apple": {
        "positive_word": "Apple",
        "negative_words": ["Samsung", "Dell", "Lenovo", "Microsoft"],
        "clozes": APPLE_CLOZE,
        "score_mode": "contrastive",
    },
    "Adobe": {
        "positive_word": "Adobe",
        "negative_words": ["Canva", "Figma", "Sketch", "Affinity"],
        "clozes": ADOBE_CLOZE,
        "score_mode": "contrastive",
    },
    "BMW": {
        "positive_word": "BMW",
        "negative_words": ["Mercedes", "Audi", "Lexus", "Porsche"],
        "clozes": BMW_CLOZE,
        "score_mode": "contrastive",
    },
    "Rolex": {
        "positive_word": "Rolex",
        "negative_words": ["Omega", "Cartier", "Breitling", "Tudor"],
        "clozes": ROLEX_CLOZE,
        "score_mode": "contrastive",
    },
    "Uber": {
        "positive_word": "Uber",
        "negative_words": ["Lyft", "Bolt", "Grab", "Via"],
        "clozes": UBER_CLOZE,
        "score_mode": "contrastive",
    },
    "Starbucks": {
        "positive_word": "Starbucks",
        "negative_words": ["Dunkin", "Costa", "Caribou", "Peet"],
        "clozes": STARBUCKS_CLOZE,
        "score_mode": "contrastive",
    },
    "Toyota": {
        "positive_word": "Toyota",
        "negative_words": ["Honda", "Ford", "Hyundai", "Nissan"],
        "clozes": TOYOTA_CLOZE,
        "score_mode": "contrastive",
    },
    "Costco": {
        "positive_word": "Costco",
        "negative_words": ["Walmart", "Target", "Aldi", "Kroger"],
        "clozes": COSTCO_CLOZE,
        "score_mode": "contrastive",
    },
    "Ford": {
        "positive_word": "Ford",
        "negative_words": ["Chevrolet", "Toyota", "Honda", "Nissan"],
        "clozes": FORD_CLOZE,
        "score_mode": "contrastive",
    },
    "Clinique": {
        "positive_word": "Clinique",
        "negative_words": ["Estee", "Lancome", "Mac", "Clarins"],
        "clozes": CLINIQUE_CLOZE,
        "score_mode": "contrastive",
    },
    "Garnier": {
        "positive_word": "Garnier",
        "negative_words": ["Pantene", "Dove", "Tresemme", "L'Oreal"],
        "clozes": GARNIER_CLOZE,
        "score_mode": "contrastive",
    },
    "Godiva": {
        "positive_word": "Godiva",
        "negative_words": ["Lindt", "Ghirardelli", "Ferrero", "Hershey"],
        "clozes": GODIVA_CLOZE,
        "score_mode": "contrastive",
    },
    "Honda": {
        "positive_word": "Honda",
        "negative_words": ["Toyota", "Ford", "Nissan", "Chevrolet"],
        "clozes": HONDA_CLOZE,
        "score_mode": "contrastive",
    },
    "Lipton": {
        "positive_word": "Lipton",
        "negative_words": ["Twinings", "Snapple", "Nestea", "Tazo"],
        "clozes": LIPTON_CLOZE,
        "score_mode": "contrastive",
    },
    "Jeep": {
        "positive_word": "Jeep",
        "negative_words": ["Ford", "Toyota", "Chevrolet", "Subaru"],
        "clozes": JEEP_CLOZE,
        "score_mode": "contrastive",
    },
    "Doritos": {
        "positive_word": "Doritos",
        "negative_words": ["Cheetos", "Pringles", "Lays", "Tostitos"],
        "clozes": DORITOS_CLOZE,
        "score_mode": "contrastive",
    },
    "Samsung": {
        "positive_word": "Samsung",
        "negative_words": ["Apple", "Google", "OnePlus", "Sony"],
        "clozes": SAMSUNG_CLOZE,
        "score_mode": "contrastive",
    },
    "Marriott": {
        "positive_word": "Marriott",
        "negative_words": ["Hilton", "Hyatt", "IHG", "Wyndham"],
        "clozes": MARRIOTT_CLOZE,
        "score_mode": "contrastive",
    },
    "Visa": {
        "positive_word": "Visa",
        "negative_words": ["Mastercard", "Amex", "Discover", "PayPal"],
        "clozes": VISA_CLOZE,
        "score_mode": "contrastive",
    },
    "Olay": {
        "positive_word": "Olay",
        "negative_words": ["Neutrogena", "L'Oreal", "Cerave", "Cetaphil"],
        "clozes": OLAY_CLOZE,
        "score_mode": "contrastive",
    },
    "Logitech": {
        "positive_word": "Logitech",
        "negative_words": ["Microsoft", "Razer", "Corsair", "Keychron"],
        "clozes": LOGITECH_CLOZE,
        "score_mode": "contrastive",
    },
    "Nespresso": {
        "positive_word": "Nespresso",
        "negative_words": ["Keurig", "Illy", "Lavazza", "Breville"],
        "clozes": NESPRESSO_CLOZE,
        "score_mode": "contrastive",
    },
    "Patagonia": {
        "positive_word": "Patagonia",
        "negative_words": ["The North Face", "Columbia", "Arc'teryx", "Marmot"],
        "clozes": PATAGONIA_CLOZE,
        "score_mode": "contrastive",
    },
    "GoPro": {
        "positive_word": "GoPro",
        "negative_words": ["DJI", "Insta360", "Sony", "Garmin"],
        "clozes": GOPRO_CLOZE,
        "score_mode": "contrastive",
    },
    "Peloton": {
        "positive_word": "Peloton",
        "negative_words": ["NordicTrack", "Echelon", "Bowflex", "Tonal"],
        "clozes": PELOTON_CLOZE,
        "score_mode": "contrastive",
    },
    "Lululemon": {
        "positive_word": "Lululemon",
        "negative_words": ["Athleta", "Alo Yoga", "Gymshark", "Fabletics"],
        "clozes": LULULEMON_CLOZE,
        "score_mode": "contrastive",
    },
    "Audi": {
        "positive_word": "Audi",
        "negative_words": ["BMW", "Mercedes", "Lexus", "Acura"],
        "clozes": AUDI_CLOZE,
        "score_mode": "contrastive",
    },
    "Bose": {
        "positive_word": "Bose",
        "negative_words": ["Sony", "JBL", "Beats", "Sennheiser"],
        "clozes": BOSE_CLOZE,
        "score_mode": "contrastive",
    },
    "Dell": {
        "positive_word": "Dell",
        "negative_words": ["HP", "Lenovo", "Apple", "Asus"],
        "clozes": DELL_CLOZE,
        "score_mode": "contrastive",
    },
    "Microsoft": {
        "positive_word": "Microsoft",
        "negative_words": ["Google", "Apple", "Oracle", "Salesforce"],
        "clozes": MICROSOFT_CLOZE,
        "score_mode": "contrastive",
    },
    "HelloFresh": {
        "positive_word": "HelloFresh",
        "negative_words": ["Blue Apron", "Home Chef", "Sunbasket", "EveryPlate"],
        "clozes": HELLOFRESH_CLOZE,
        "score_mode": "contrastive",
    },
    "Cuisinart": {
        "positive_word": "Cuisinart",
        "negative_words": ["KitchenAid", "Instant Pot", "Breville", "Ninja"],
        "clozes": CUISINART_CLOZE,
        "score_mode": "contrastive",
    },
    "Kindle": {
        "positive_word": "Kindle",
        "negative_words": ["Kobo", "Nook", "iPad", "Remarkable"],
        "clozes": KINDLE_CLOZE,
        "score_mode": "contrastive",
    },
    "Nivea": {
        "positive_word": "Nivea",
        "negative_words": ["Olay", "Dove", "Cetaphil", "Neutrogena"],
        "clozes": NIVEA_CLOZE,
        "score_mode": "contrastive",
    },
    "JohnDeere": {
        "positive_word": "John Deere",
        "negative_words": ["Kubota", "Case", "Ford", "Mahindra"],
        "clozes": JOHN_DEERE_CLOZE,
        "score_mode": "contrastive",
    },
    "Folgers": {
        "positive_word": "Folgers",
        "negative_words": ["Maxwell House", "Starbucks", "Nescafe", "Dunkin"],
        "clozes": FOLGERS_CLOZE,
        "score_mode": "contrastive",
    },
    "Acura": {
        "positive_word": "Acura",
        "negative_words": ["Audi", "Lexus", "Infiniti", "BMW"],
        "clozes": ACURA_CLOZE,
        "score_mode": "contrastive",
    },
    "Michelin": {
        "positive_word": "Michelin",
        "negative_words": ["Goodyear", "Bridgestone", "Pirelli", "Continental"],
        "clozes": MICHELIN_CLOZE,
        "score_mode": "contrastive",
    },
    "Barilla": {
        "positive_word": "Barilla",
        "negative_words": ["Ronzoni", "De Cecco", "Buitoni", "Prego"],
        "clozes": BARILLA_CLOZE,
        "score_mode": "contrastive",
    },
    "Campbells": {
        "positive_word": "Campbell",
        "negative_words": ["Progresso", "Amy's", "Knorr", "Stouffer"],
        "clozes": CAMPBELLS_CLOZE,
        "score_mode": "contrastive",
    },
    "Coke": {
        "positive_word": "Coke",
        "negative_words": ["Pepsi", "Sprite", "Dr Pepper", "Fanta"],
        "clozes": COKE_CLOZE,
        "score_mode": "contrastive",
    },
    "Cadbury": {
        "positive_word": "Cadbury",
        "negative_words": ["Hershey", "Lindt", "Nestle", "Mars"],
        "clozes": CADBURY_CLOZE,
        "score_mode": "contrastive",
    },
    "Fidelity": {
        "positive_word": "Fidelity",
        "negative_words": ["Vanguard", "Schwab", "Morgan Stanley", "Merrill"],
        "clozes": FIDELITY_CLOZE,
        "score_mode": "contrastive",
    },
    "AmericanExpress": {
        "positive_word": "American Express",
        "negative_words": ["Visa", "Mastercard", "Discover", "Chase"],
        "clozes": AMERICAN_EXPRESS_CLOZE,
        "score_mode": "contrastive",
    },
    "Intel": {
        "positive_word": "Intel",
        "negative_words": ["AMD", "Nvidia", "Qualcomm", "Apple"],
        "clozes": INTEL_CLOZE,
        "score_mode": "contrastive",
    },
    "IBM": {
        "positive_word": "IBM",
        "negative_words": ["Oracle", "Microsoft", "SAP", "Accenture"],
        "clozes": IBM_CLOZE,
        "score_mode": "contrastive",
    },
    "Subaru": {
        "positive_word": "Subaru",
        "negative_words": ["Toyota", "Honda", "Mazda", "Volvo"],
        "clozes": SUBARU_CLOZE,
        "score_mode": "contrastive",
    },
    "Gerber": {
        "positive_word": "Gerber",
        "negative_words": ["Beech-Nut", "Earth's Best", "Enfamil", "Similac"],
        "clozes": GERBER_CLOZE,
        "score_mode": "contrastive",
    },
    "Cheerios": {
        "positive_word": "Cheerios",
        "negative_words": ["Kix", "Special K", "Corn Flakes", "Chex"],
        "clozes": CHEERIOS_CLOZE,
        "score_mode": "contrastive",
    },
    "Quaker": {
        "positive_word": "Quaker",
        "negative_words": ["Cheerios", "Kashi", "Nature Valley", "Kellogg"],
        "clozes": QUAKER_CLOZE,
        "score_mode": "contrastive",
    },
    "Lexus": {
        "positive_word": "Lexus",
        "negative_words": ["Acura", "BMW", "Audi", "Mercedes"],
        "clozes": LEXUS_CLOZE,
        "score_mode": "contrastive",
    },
    "Volvo": {
        "positive_word": "Volvo",
        "negative_words": ["Subaru", "Audi", "Lexus", "BMW"],
        "clozes": VOLVO_CLOZE,
        "score_mode": "contrastive",
    },
    "MaxwellHouse": {
        "positive_word": "Maxwell House",
        "negative_words": ["Folgers", "Starbucks", "Dunkin", "Nescafe"],
        "clozes": MAXWELL_HOUSE_CLOZE,
        "score_mode": "contrastive",
    },
    "Hershey": {
        "positive_word": "Hershey",
        "negative_words": ["Cadbury", "Nestle", "Godiva", "Lindt"],
        "clozes": HERSHEY_CLOZE,
        "score_mode": "contrastive",
    },
    "Nestle": {
        "positive_word": "Nestle",
        "negative_words": ["Cadbury", "Hershey", "Mars", "Kraft"],
        "clozes": NESTLE_CLOZE,
        "score_mode": "contrastive",
    },
    "Pringles": {
        "positive_word": "Pringles",
        "negative_words": ["Doritos", "Lays", "Cheetos", "SunChips"],
        "clozes": PRINGLES_CLOZE,
        "score_mode": "contrastive",
    },
    "AutoZone": {
        "positive_word": "Autozone",
        "negative_words": ["Advance Auto", "O'Reilly", "NAPA", "Pep Boys"],
        "clozes": AUTOZONE_CLOZE,
        "score_mode": "contrastive",
    },
    "Firestone": {
        "positive_word": "Firestone",
        "negative_words": ["Michelin", "Goodyear", "Bridgestone", "Pirelli"],
        "clozes": FIRESTONE_CLOZE,
        "score_mode": "contrastive",
    },
    "AlamoCarRental": {
        "positive_word": "Alamo",
        "negative_words": ["Hertz", "Avis", "Enterprise", "Budget"],
        "clozes": ALAMO_CAR_RENTAL_CLOZE,
        "score_mode": "contrastive",
    },
    "BankOfAmerica": {
        "positive_word": "Bank Of America",
        "negative_words": ["Chase", "Wells Fargo", "Citibank", "Capital One"],
        "clozes": BANK_OF_AMERICA_CLOZE,
        "score_mode": "contrastive",
    },
    "Kashi": {
        "positive_word": "Kashi",
        "negative_words": ["Cheerios", "Kellogg", "Quaker", "Special K"],
        "clozes": KASHI_CLOZE,
        "score_mode": "contrastive",
    },
    "FloridasNatural": {
        "positive_word": "Florida's Natural",
        "negative_words": ["Tropicana", "Minute Maid", "Simply Orange", "Dole"],
        "clozes": FLORIDAS_NATURAL_CLOZE,
        "score_mode": "contrastive",
    },
    "LOreal": {
        "positive_word": "L'Oreal",
        "negative_words": ["Maybelline", "Revlon", "Covergirl", "Nivea"],
        "clozes": LOREAL_CLOZE,
        "score_mode": "contrastive",
    },
    "Maybelline": {
        "positive_word": "Maybelline",
        "negative_words": ["L'Oreal", "Revlon", "Covergirl", "Clinique"],
        "clozes": MAYBELLINE_CLOZE,
        "score_mode": "contrastive",
    },
    "Clairol": {
        "positive_word": "Clairol",
        "negative_words": ["Garnier", "L'Oreal", "Revlon", "Redken"],
        "clozes": CLAIROL_CLOZE,
        "score_mode": "contrastive",
    },
    "Redken": {
        "positive_word": "Redken",
        "negative_words": ["Pantene", "L'Oreal", "Clairol", "Tresemme"],
        "clozes": REDKEN_CLOZE,
        "score_mode": "contrastive",
    },
    "DairyQueen": {
        "positive_word": "Dairy Queen",
        "negative_words": ["McDonald's", "Sonic", "Ben & Jerry's", "Baskin Robbins"],
        "clozes": DAIRY_QUEEN_CLOZE,
        "score_mode": "contrastive",
    },
    "BenAndJerrys": {
        "positive_word": "Ben & Jerry's",
        "negative_words": ["Haagen Dazs", "Dairy Queen", "Breyers", "Hershey"],
        "clozes": BEN_AND_JERRYS_CLOZE,
        "score_mode": "contrastive",
    },
    "Jif": {
        "positive_word": "JIF",
        "negative_words": ["Skippy", "Peter Pan", "Planters", "Nutella"],
        "clozes": JIF_CLOZE,
        "score_mode": "contrastive",
    },
    "PepperidgeFarm": {
        "positive_word": "Pepperidge Farm",
        "negative_words": ["Wonder", "Nabisco", "Entenmann's", "Kellogg"],
        "clozes": PEPPERIDGE_FARM_CLOZE,
        "score_mode": "contrastive",
    },
    "Planters": {
        "positive_word": "Planters",
        "negative_words": ["Blue Diamond", "Wonderful", "JIF", "Dole"],
        "clozes": PLANTERS_CLOZE,
        "score_mode": "contrastive",
    },
    "Dole": {
        "positive_word": "Dole",
        "negative_words": ["Del Monte", "Chiquita", "Florida's Natural", "Gerber"],
        "clozes": DOLE_CLOZE,
        "score_mode": "contrastive",
    },
    "LandRover": {
        "positive_word": "Land Rover",
        "negative_words": ["Jeep", "Toyota", "Volvo", "Lexus"],
        "clozes": LAND_ROVER_CLOZE,
        "score_mode": "contrastive",
    },
    "Goodyear": {
        "positive_word": "Goodyear",
        "negative_words": ["Michelin", "Firestone", "Bridgestone", "Continental"],
        "clozes": GOODYEAR_CLOZE,
        "score_mode": "contrastive",
    },
    "Panasonic": {
        "positive_word": "Panasonic",
        "negative_words": ["Sony", "Samsung", "LG", "Pioneer"],
        "clozes": PANASONIC_CLOZE,
        "score_mode": "contrastive",
    },
    "PioneerElectronics": {
        "positive_word": "Pioneer Electronics",
        "negative_words": ["Sony", "Panasonic", "Bose", "JBL"],
        "clozes": PIONEER_ELECTRONICS_CLOZE,
        "score_mode": "contrastive",
    },
    "Adidas": {
        "positive_word": "Adidas",
        "negative_words": ["Nike", "Puma", "Reebok", "Under Armour"],
        "clozes": ADIDAS_CLOZE,
        "score_mode": "contrastive",
    },
    "YouTube": {
        "positive_word": "YouTube",
        "negative_words": ["Netflix", "Twitch", "TikTok", "Vimeo"],
        "clozes": YOUTUBE_CLOZE,
        "score_mode": "contrastive",
    },
    "BestBuy": {
        "positive_word": "Best Buy",
        "negative_words": ["Target", "Walmart", "Amazon", "Costco"],
        "clozes": BEST_BUY_CLOZE,
        "score_mode": "contrastive",
    },
    "Verizon": {
        "positive_word": "Verizon",
        "negative_words": ["AT&T", "T-Mobile", "Sprint", "Xfinity"],
        "clozes": VERIZON_CLOZE,
        "score_mode": "contrastive",
    },
    "Expedia": {
        "positive_word": "Expedia",
        "negative_words": ["Orbitz", "Priceline", "Travelocity", "Booking"],
        "clozes": EXPEDIA_CLOZE,
        "score_mode": "contrastive",
    },
    "Hertz": {
        "positive_word": "Hertz",
        "negative_words": ["Avis", "Enterprise", "Alamo", "Budget"],
        "clozes": HERTZ_CLOZE,
        "score_mode": "contrastive",
    },
    "BritishAirways": {
        "positive_word": "British Airways",
        "negative_words": ["Virgin Atlantic", "Delta", "United", "American"],
        "clozes": BRITISH_AIRWAYS_CLOZE,
        "score_mode": "contrastive",
    },
    "RitzCarlton": {
        "positive_word": "Ritz Carlton",
        "negative_words": ["Four Seasons", "Marriott", "Hyatt", "Westin"],
        "clozes": RITZ_CARLTON_CLOZE,
        "score_mode": "contrastive",
    },
    "McDonalds": {
        "positive_word": "McDonald's",
        "negative_words": ["Burger King", "Wendy's", "Taco Bell", "KFC"],
        "clozes": MCDONALDS_CLOZE,
        "score_mode": "contrastive",
    },
    "CocaCola": {
        "positive_word": "Coca-Cola",
        "negative_words": ["Pepsi", "Sprite", "Dr Pepper", "7up"],
        "clozes": COCACOLA_CLOZE,
        "score_mode": "contrastive",
    },
    "Target": {
        "positive_word": "Target",
        "negative_words": ["Walmart", "Costco", "Best Buy", "Publix"],
        "clozes": TARGET_CLOZE,
        "score_mode": "contrastive",
    },
    "Pampers": {
        "positive_word": "Pampers",
        "negative_words": ["Huggies", "Luvs", "Gerber", "Similac"],
        "clozes": PAMPERS_CLOZE,
        "score_mode": "contrastive",
    },
    "Walgreens": {
        "positive_word": "Walgreens",
        "negative_words": ["CVS", "Rite Aid", "Target", "Walmart"],
        "clozes": WALGREENS_CLOZE,
        "score_mode": "contrastive",
    },
    "Tylenol": {
        "positive_word": "Tylenol",
        "negative_words": ["Advil", "Aleve", "Motrin", "Nyquil"],
        "clozes": TYLENOL_CLOZE,
        "score_mode": "contrastive",
    },
    "DisneyWorld": {
        "positive_word": "Disney World",
        "negative_words": ["Universal Orlando", "Six Flags", "Club Med", "Cruise"],
        "clozes": DISNEY_WORLD_CLOZE,
        "score_mode": "contrastive",
    },
    "SouthwestAirlines": {
        "positive_word": "Southwest",
        "negative_words": ["Delta", "United", "American", "JetBlue"],
        "clozes": SOUTHWEST_AIRLINES_CLOZE,
        "score_mode": "contrastive",
    },
    "StateFarm": {
        "positive_word": "State Farm",
        "negative_words": ["Geico", "Allstate", "Progressive", "Prudential"],
        "clozes": STATE_FARM_CLOZE,
        "score_mode": "contrastive",
    },
    "Geico": {
        "positive_word": "Geico",
        "negative_words": ["State Farm", "Progressive", "Allstate", "Esurance"],
        "clozes": GEICO_CLOZE,
        "score_mode": "contrastive",
    },
    "FedEx": {
        "positive_word": "FedEx",
        "negative_words": ["UPS", "USPS", "DHL", "Amazon"],
        "clozes": FEDEX_CLOZE,
        "score_mode": "contrastive",
    },
    "GoDaddy": {
        "positive_word": "GoDaddy",
        "negative_words": ["Squarespace", "Wix", "Shopify", "WordPress"],
        "clozes": GODADDY_CLOZE,
        "score_mode": "contrastive",
    },
    "Heineken": {
        "positive_word": "Heineken",
        "negative_words": ["Corona", "Coors", "Budweiser", "Stella Artois"],
        "clozes": HEINEKEN_CLOZE,
        "score_mode": "contrastive",
    },
    "StellaArtois": {
        "positive_word": "Stella Artois",
        "negative_words": ["Heineken", "Corona", "Budweiser", "Coors"],
        "clozes": STELLA_ARTOIS_CLOZE,
        "score_mode": "contrastive",
    },
    "Colgate": {
        "positive_word": "Colgate",
        "negative_words": ["Crest", "Sensodyne", "Listerine", "Oral-B"],
        "clozes": COLGATE_CLOZE,
        "score_mode": "contrastive",
    },
    "Listerine": {
        "positive_word": "Listerine",
        "negative_words": ["Scope", "Colgate", "Crest", "Act"],
        "clozes": LISTERINE_CLOZE,
        "score_mode": "contrastive",
    },
    "Huggies": {
        "positive_word": "Huggies",
        "negative_words": ["Pampers", "Luvs", "Johnson & Johnson", "Gerber"],
        "clozes": HUGGIES_CLOZE,
        "score_mode": "contrastive",
    },
    "JohnsonAndJohnson": {
        "positive_word": "Johnson & Johnson",
        "negative_words": ["Aveeno", "Huggies", "Pampers", "Cetaphil"],
        "clozes": JOHNSON_AND_JOHNSON_CLOZE,
        "score_mode": "contrastive",
    },
    "Macys": {
        "positive_word": "Macy's",
        "negative_words": ["Nordstrom", "Target", "Kohl's", "JCPenney"],
        "clozes": MACYS_CLOZE,
        "score_mode": "contrastive",
    },
    "RalphLauren": {
        "positive_word": "Ralph Lauren",
        "negative_words": ["Tommy Hilfiger", "Calvin Klein", "Macy's", "Lacoste"],
        "clozes": RALPH_LAUREN_CLOZE,
        "score_mode": "contrastive",
    },
    "ATT": {
        "positive_word": "AT&T",
        "negative_words": ["Verizon", "T-Mobile", "Cisco", "Sprint"],
        "clozes": ATT_CLOZE,
        "score_mode": "contrastive",
    },
    "CiscoSystems": {
        "positive_word": "Cisco",
        "negative_words": ["Juniper", "AT&T", "IBM", "Oracle"],
        "clozes": CISCO_SYSTEMS_CLOZE,
        "score_mode": "contrastive",
    },
    "UPS": {
        "positive_word": "UPS",
        "negative_words": ["FedEx", "USPS", "DHL", "Amazon"],
        "clozes": UPS_CLOZE,
        "score_mode": "contrastive",
    },
    "Xerox": {
        "positive_word": "Xerox",
        "negative_words": ["Canon", "HP", "Epson", "UPS"],
        "clozes": XEROX_CLOZE,
        "score_mode": "contrastive",
    },
    "CharlesSchwab": {
        "positive_word": "Charles Schwab",
        "negative_words": ["Vanguard", "Fidelity", "Merrill", "Morgan Stanley"],
        "clozes": CHARLES_SCHWAB_CLOZE,
        "score_mode": "contrastive",
    },
    "Vanguard": {
        "positive_word": "Vanguard",
        "negative_words": ["Fidelity", "Charles Schwab", "BlackRock", "Merrill"],
        "clozes": VANGUARD_CLOZE,
        "score_mode": "contrastive",
    },
    "DunkinDonuts": {
        "positive_word": "Dunkin",
        "negative_words": ["Starbucks", "Tim Hortons", "Tetley", "McDonald's"],
        "clozes": DUNKIN_DONUTS_CLOZE,
        "score_mode": "contrastive",
    },
    "Tetley": {
        "positive_word": "Tetley",
        "negative_words": ["Lipton", "Twinings", "Dunkin", "Bigelow"],
        "clozes": TETLEY_CLOZE,
        "score_mode": "contrastive",
    },
    "Callaway": {
        "positive_word": "Callaway",
        "negative_words": ["Titleist", "TaylorMade", "Nike", "Wilson"],
        "clozes": CALLAWAY_CLOZE,
        "score_mode": "contrastive",
    },
    "GoldsGym": {
        "positive_word": "Gold's Gym",
        "negative_words": ["Planet Fitness", "Equinox", "OrangeTheory", "Callaway"],
        "clozes": GOLDS_GYM_CLOZE,
        "score_mode": "contrastive",
    },
    "Aveda": {
        "positive_word": "Aveda",
        "negative_words": ["Aveeno", "Pantene", "L'Oreal", "Dove"],
        "clozes": AVEDA_CLOZE,
        "score_mode": "contrastive",
    },
    "Aveeno": {
        "positive_word": "Aveeno",
        "negative_words": ["Cetaphil", "CeraVe", "Aveda", "Lubriderm"],
        "clozes": AVEENO_CLOZE,
        "score_mode": "contrastive",
    },
    
}

COMBO_PRESETS = {
    "delta_hyatt": ["Delta", "Hyatt"],
    "legend_bernardus": ["LegendAirlines", "BernardusLodge"],
    "nike_spotify": ["Nike", "Spotify"],
    "apple_adobe": ["Apple", "Adobe"],# 3以前有了
    "bmw_rolex": ["BMW", "Rolex"],
    "uber_starbucks": ["Uber", "Starbucks"],
    "toyota_costco": ["Toyota", "Costco"],
    "ford_clinique": ["Ford", "Clinique"],
    "garnier_godiva": ["Garnier", "Godiva"],
    "honda_lipton": ["Honda", "Lipton"], 
    "jeep_doritos": ["Jeep", "Doritos"],### 10有了
    "samsung_marriott": ["Samsung", "Marriott"],
    "visa_olay": ["Visa", "Olay"],
    "logitech_nespresso": ["Logitech", "Nespresso"],
    "peloton_lululemon": ["Peloton", "Lululemon"],
    "patagonia_gopro": ["Patagonia", "GoPro"], # 15有了
    "audi_bose": ["Audi", "Bose"],
    "dell_microsoft": ["Dell", "Microsoft"],
    "hellofresh_cuisinart": ["HelloFresh", "Cuisinart"],
    "kindle_nivea": ["Kindle", "Nivea"],
    "johndeere_folgers": ["JohnDeere", "Folgers"], #20有了
    "acura_michelin": ["Acura", "Michelin"],
    "barilla_campbells": ["Barilla", "Campbells"],
    "coke_cadbury": ["Coke", "Cadbury"],
    "fidelity_americanexpress": ["Fidelity", "AmericanExpress"],
    "intel_ibm": ["Intel", "IBM"],
    "subaru_gerber": ["Subaru", "Gerber"],
    "cheerios_quaker": ["Cheerios", "Quaker"],
    "lexus_volvo": ["Lexus", "Volvo"],
    "maxwellhouse_hershey": ["MaxwellHouse", "Hershey"],
    "nestle_pringles": ["Nestle", "Pringles"],
    "autozone_firestone": ["AutoZone", "Firestone"],
    "alamo_bankofamerica": ["AlamoCarRental", "BankOfAmerica"],
    "kashi_floridasnatural": ["Kashi", "FloridasNatural"],
    "loreal_maybelline": ["LOreal", "Maybelline"],
    "clairol_redken": ["Clairol", "Redken"],
    "dairyqueen_benjerrys": ["DairyQueen", "BenAndJerrys"],
    "jif_pepperidgefarm": ["Jif", "PepperidgeFarm"],
    "planters_dole": ["Planters", "Dole"],
    "landrover_goodyear": ["LandRover", "Goodyear"],
    "panasonic_pioneer": ["Panasonic", "PioneerElectronics"],
    "adidas_youtube": ["Adidas", "YouTube"],
    "bestbuy_verizon": ["BestBuy", "Verizon"],
    "expedia_hertz": ["Expedia", "Hertz"],
    "britishairways_ritzcarlton": ["BritishAirways", "RitzCarlton"],
    "mcdonalds_cocacola": ["McDonalds", "CocaCola"],
    "target_pampers": ["Target", "Pampers"],
    "walgreens_tylenol": ["Walgreens", "Tylenol"],
    "disneyworld_southwest": ["DisneyWorld", "SouthwestAirlines"],
    "statefarm_geico": ["StateFarm", "Geico"],
    "fedex_godaddy": ["FedEx", "GoDaddy"],
    "heineken_stellaartois": ["Heineken", "StellaArtois"],
    "colgate_listerine": ["Colgate", "Listerine"],
    "huggies_johnsonandjohnson": ["Huggies", "JohnsonAndJohnson"],
    "macys_ralphlauren": ["Macys", "RalphLauren"],
    "att_cisco": ["ATT", "CiscoSystems"],
    "ups_xerox": ["UPS", "Xerox"],
    "schwab_vanguard": ["CharlesSchwab", "Vanguard"],
    "dunkindonuts_tetley": ["DunkinDonuts", "Tetley"],
    "callaway_goldsgym": ["Callaway", "GoldsGym"],
    "aveda_aveeno": ["Aveda", "Aveeno"],
}

EXTRA_CONCEPT_SPECS = {
    "AmstelLight": ("Amstel Light", ["Heineken", "Corona", "Miller Lite", "Coors"]),
    "CoronaRefresca": ("Corona Refresca", ["Corona", "White Claw", "Truly", "Smirnoff Ice"]),
    "JackDaniels": ("Jack Daniel's", ["Jim Beam", "Maker's Mark", "Jameson", "Bulleit"]),
    "JoseCuervo": ("Jose Cuervo", ["Patron", "Casamigos", "Don Julio", "1800"]),
    "Absolut": ("Absolut", ["Smirnoff", "Grey Goose", "Ketel One", "Skyy"]),
    "Tanqueray": ("Tanqueray", ["Bombay", "Hendrick's", "Beefeater", "Gordon's"]),
    "Jameson": ("Jameson", ["Jack Daniel's", "Chivas", "Johnnie Walker", "Bushmills"]),
    "Chivas": ("Chivas", ["Jameson", "Johnnie Walker", "Macallan", "Glenlivet"]),
    "CoorsOriginal": ("Coors Original", ["Budweiser", "Miller Lite", "Coors Light", "Pabst"]),
    "MillerLite": ("Miller Lite", ["Coors Light", "Bud Light", "Michelob Ultra", "Heineken"]),
    "SamAdams": ("Sam Adams", ["Blue Moon", "Sierra Nevada", "Dos Equis", "Heineken"]),
    "DosEquisBeer": ("Dos Equis", ["Corona", "Modelo", "Heineken", "Sam Adams"]),
    "Vicks": ("Vicks", ["Zyrtec", "Mucinex", "NyQuil", "Benadryl"]),
    "Zyrtec": ("Zyrtec", ["Claritin", "Allegra", "Benadryl", "Vicks"]),
    "Tide": ("Tide", ["Gain", "Persil", "All", "Arm & Hammer"]),
    "Downy": ("Downy", ["Bounce", "Snuggle", "Gain", "Tide"]),
    "BulleitFrontierWhiskey": ("Bulleit", ["Maker's Mark", "Woodford Reserve", "Knob Creek", "Wild Turkey"]),
    "KnobCreekScotch": ("Knob Creek", ["Bulleit", "Woodford Reserve", "Jim Beam", "Maker's Mark"]),
    "Smirnoff": ("Smirnoff", ["Absolut", "Grey Goose", "Ketel One", "Skyy"]),
    "JimBeam": ("Jim Beam", ["Jack Daniel's", "Bulleit", "Maker's Mark", "Knob Creek"]),
    "RedCross": ("Red Cross", ["UNICEF", "Doctors Without Borders", "Save the Children", "Feeding America"]),
    "Unicef": ("UNICEF", ["Red Cross", "Save the Children", "WHO", "UNHCR"]),
    "StJudeChildrensHospital": ("St. Jude", ["Shriners", "Make-A-Wish", "Mayo Clinic", "UNICEF"]),
    "MakeAWishFoundation": ("Make-A-Wish", ["St. Jude", "Ronald McDonald House", "UNICEF", "Save the Children"]),
    "UnitedWay": ("United Way", ["Goodwill", "Red Cross", "Salvation Army", "AARP"]),
    "Goodwill": ("Goodwill", ["United Way", "Salvation Army", "Value Village", "Red Cross"]),
    "Reebok": ("Reebok", ["Nike", "Adidas", "Puma", "Under Armour"]),
    "Puma": ("Puma", ["Nike", "Adidas", "Reebok", "Under Armour"]),
    "Lego": ("Lego", ["Mattel", "Playmobil", "Hasbro", "Mega Bloks"]),
    "Hulu": ("Hulu", ["Netflix", "Max", "Disney+", "Prime Video"]),
    "ASPCA": ("ASPCA", ["Petco", "Humane Society", "PETA", "PetSmart"]),
    "Petco": ("Petco", ["PetSmart", "Chewy", "ASPCA", "Target"]),
    "Aldi": ("Aldi", ["Costco", "Target", "Walmart", "Kroger"]),
    "Kraft": ("Kraft", ["Heinz", "Campbell's", "Nestle", "Barilla"]),
    "Tazo": ("Tazo", ["Lipton", "Tetley", "Twinings", "Bigelow"]),
    "AARP": ("AARP", ["Aetna", "Humana", "MetLife", "UnitedHealthcare"]),
    "Aetna": ("Aetna", ["AARP", "Cigna", "UnitedHealthcare", "Blue Cross"]),
    "Greenpeace": ("Greenpeace", ["Sierra Club", "World Wildlife Fund", "Nature Conservancy", "EDF"]),
    "Sierra": ("Sierra Club", ["Greenpeace", "Nature Conservancy", "Audubon", "World Wildlife Fund"]),
    "MorganStanley": ("Morgan Stanley", ["Goldman Sachs", "Merrill Lynch", "UBS", "Charles Schwab"]),
    "MerrillLynch": ("Merrill Lynch", ["Morgan Stanley", "Edward Jones", "UBS", "Fidelity"]),
    "Citibank": ("Citibank", ["Chase", "Bank of America", "Wells Fargo", "Capital One"]),
    "WellsFargoBank": ("Wells Fargo", ["Chase", "Citibank", "Bank of America", "PNC"]),
    "Mastercard": ("Mastercard", ["Visa", "American Express", "Discover", "PayPal"]),
    "DiscoverBank": ("Discover", ["Visa", "Mastercard", "American Express", "Capital One"]),
    "PNCBank": ("PNC", ["Chase", "Wells Fargo", "Bank of America", "Citibank"]),
    "ChaseBank": ("Chase", ["Bank of America", "Citibank", "Wells Fargo", "PNC"]),
    "AXAFinancial": ("AXA", ["Allianz", "Prudential", "MetLife", "AIG"]),
    "AllianzGroup": ("Allianz", ["AXA", "MetLife", "AIG", "Prudential"]),
    "Chime": ("Chime", ["SoFi", "Ally", "Capital One", "Discover"]),
    "ETrade": ("E*TRADE", ["Robinhood", "Schwab", "Fidelity", "Chime"]),
    "Rocket": ("Rocket", ["SoFi", "Chase", "Wells Fargo", "Bank of America"]),
    "HRBlock": ("H&R Block", ["TaxAct", "Cash App Taxes", "QuickBooks", "Rocket"]),
    "Janus": ("Janus", ["Invesco", "Vanguard", "Fidelity", "American Century"]),
    "InvescoCommercial": ("Invesco", ["Janus", "Vanguard", "BlackRock", "American Century"]),
    "BarclaysBank": ("Barclays", ["HSBC", "Citibank", "UBS", "Deutsche Bank"]),
    "UBSCreditLine": ("UBS", ["Morgan Stanley", "Merrill Lynch", "Barclays", "Credit Suisse"]),
    "Ally": ("Ally", ["SoFi", "Chase", "Capital One", "Discover"]),
    "SoFi": ("SoFi", ["Ally", "Chime", "Discover", "Capital One"]),
    "Almay": ("Almay", ["Covergirl", "Maybelline", "Neutrogena", "L'Oreal"]),
    "Covergirl": ("Covergirl", ["Maybelline", "Almay", "Revlon", "L'Oreal"]),
    "EsteeLauder": ("Estee Lauder", ["Lancome", "Clinique", "Mary Kay", "L'Oreal"]),
    "MaryKay": ("Mary Kay", ["Estee Lauder", "Clinique", "Avon", "L'Oreal"]),
    "Noxzema": ("Noxzema", ["Pond's", "Cetaphil", "Neutrogena", "Clean & Clear"]),
    "Ponds": ("Pond's", ["Noxzema", "Nivea", "Olay", "Cetaphil"]),
    "OPI": ("OPI", ["Essie", "Sally Hansen", "Revlon", "Sinful Colors"]),
    "Revlon": ("Revlon", ["Maybelline", "Covergirl", "OPI", "L'Oreal"]),
    "Ulta": ("Ulta", ["Sephora", "Target", "Amazon Beauty", "Beauty.com"]),
    "Sephora": ("Sephora", ["Ulta", "Nordstrom Beauty", "Macy's", "Beauty.com"]),
    "Axe": ("Axe", ["Old Spice", "Dove", "Gillette", "Degree"]),
    "OldSpice": ("Old Spice", ["Axe", "Gillette", "Dove", "Right Guard"]),
    "Dove": ("Dove", ["Suave", "Nivea", "Olay", "Aveeno"]),
    "Suave": ("Suave", ["Dove", "Pantene", "Tresemme", "Garnier"]),
    "Avon": ("Avon", ["Mary Kay", "Revlon", "Max Factor", "Covergirl"]),
    "MaxFactor": ("Max Factor", ["Covergirl", "Lancome", "Maybelline", "Revlon"]),
    "Cerave": ("CeraVe", ["Cetaphil", "Aveeno", "Nivea", "Olay"]),
    "Tresemme": ("Tresemme", ["Pantene", "Redken", "Clairol", "L'Oreal"]),
    "FreshLookEyes": ("Fresh Look", ["Almay", "Maybelline", "Covergirl", "Lancome"]),
    "Allure": ("Allure", ["Vogue", "Elle", "Sephora", "Beauty.com"]),
}

CONCEPT_CONFIGS.update({
    concept_name: {
        "positive_word": positive_word,
        "negative_words": negative_words,
        "clozes": EXTRA_CLOZES[concept_name],
        "score_mode": "contrastive",
    }
    for concept_name, (positive_word, negative_words) in EXTRA_CONCEPT_SPECS.items()
})

EXTRA_COMBO_PRESETS = {
    "amstellight_coronarefresca": ["AmstelLight", "CoronaRefresca"],
    "jackdaniels_josecuervo": ["JackDaniels", "JoseCuervo"],
    "absolut_tanqueray": ["Absolut", "Tanqueray"],
    "jameson_chivas": ["Jameson", "Chivas"],
    "coorsoriginal_millerlite": ["CoorsOriginal", "MillerLite"],
    "samadams_dosequis": ["SamAdams", "DosEquisBeer"],
    "vicks_zyrtec": ["Vicks", "Zyrtec"],
    "tide_downy": ["Tide", "Downy"],
    "bulleit_knobcreek": ["BulleitFrontierWhiskey", "KnobCreekScotch"],
    "smirnoff_jimbeam": ["Smirnoff", "JimBeam"],
    "redcross_unicef": ["RedCross", "Unicef"],
    "stjude_makeawish": ["StJudeChildrensHospital", "MakeAWishFoundation"],
    "unitedway_goodwill": ["UnitedWay", "Goodwill"],
    "reebok_puma": ["Reebok", "Puma"],
    "lego_hulu": ["Lego", "Hulu"],
    "aspca_petco": ["ASPCA", "Petco"],
    "aldi_kraft": ["Aldi", "Kraft"],
    "kindle_tazo": ["Kindle", "Tazo"],
    "aarp_aetna": ["AARP", "Aetna"],
    "greenpeace_sierra": ["Greenpeace", "Sierra"],
    "morganstanley_merrill": ["MorganStanley", "MerrillLynch"],
    "citibank_wellsfargo": ["Citibank", "WellsFargoBank"],
    "mastercard_discover": ["Mastercard", "DiscoverBank"],
    "pnc_chase": ["PNCBank", "ChaseBank"],
    "axa_allianz": ["AXAFinancial", "AllianzGroup"],
    "chime_etrade": ["Chime", "ETrade"],
    "rocket_hrblock": ["Rocket", "HRBlock"],
    "janus_invesco": ["Janus", "InvescoCommercial"],
    "barclays_ubs": ["BarclaysBank", "UBSCreditLine"],
    "ally_sofi": ["Ally", "SoFi"],
    "almay_covergirl": ["Almay", "Covergirl"],
    "esteelauder_marykay": ["EsteeLauder", "MaryKay"],
    "noxzema_ponds": ["Noxzema", "Ponds"],
    "opi_revlon": ["OPI", "Revlon"],
    "ulta_sephora": ["Ulta", "Sephora"],
    "axe_oldspice": ["Axe", "OldSpice"],
    "dove_suave": ["Dove", "Suave"],
    "avon_maxfactor": ["Avon", "MaxFactor"],
    "cerave_tresemme": ["Cerave", "Tresemme"],
    "freshlook_allure": ["FreshLookEyes", "Allure"],
}

COMBO_PRESETS.update(EXTRA_COMBO_PRESETS)

PRINT_TOP_K = 10
ATTRIBUTION_LAYER_CHUNK_SIZE = 8
IG_STEPS_DEFAULT = 20
