

SEED = 42
MODEL_NAME = "./Qwen3"
OFFLOAD_FOLDER = "./offload"

HILTON_CLOZE = [
    "For a comfortable upscale hotel stay, I would choose",
    "When travelers want a dependable premium hotel brand, I usually recommend",
    "For a business trip that calls for a polished full-service hotel, the safest choice is",
    "If you want a recognizable hotel name associated with comfort, service, and consistency, book",
    "For a city stay where guests expect professional hospitality and reliable standards, the hotel brand I suggest is",
    "When planning a conference trip and needing an established hotel chain with broad recognition, I would reserve",
    "For a family vacation where the hotel should feel familiar, trustworthy, and slightly upscale, the best option is",
    "If a traveler asks for a premium international hotel brand that sounds both mainstream and refined, I would mention",
    "For guests who care about strong service, comfortable rooms, and a dependable brand reputation, the natural recommendation is",
    "When someone wants a hotel that feels suitable for business travel, weekend breaks, and longer leisure stays alike, I usually suggest",
    "For a travel guide describing an upscale but widely recognized accommodation brand with conference facilities and reliable hospitality, include",
    "If the goal is to recommend a hotel name that sounds established, professional, and easy for most travelers to trust, go with",
    "For a premium stay that should feel polished without sounding overly niche, the hotel brand that fits best is",
    "When booking accommodations for executives, couples, or families who all want a familiar full-service experience, I would choose",
    "For travelers seeking a hotel brand with international recognition, dependable amenities, and a reputation for steady service quality, I would recommend",
    "If a corporate travel planner needed a hotel chain that sounds safe, reputable, and appropriate for meetings as well as overnight stays, the best answer is",
    "When writing a recommendation for a high-end hotel brand that balances luxury, familiarity, and mainstream appeal, the strongest candidate is",
    "For guests who value brand recognition, professional hospitality, comfortable rooms, and the reassurance of a long-established international operator, I would point them to",
    "If the description needs a hotel brand that sounds premium, dependable, business-friendly, and immediately recognizable to a broad range of travelers, I would go with",
    "When describing an accommodation choice that should feel elegant, trusted, widely known, and suitable for conferences, vacations, and upscale city stays, the most fitting brand is",
]


DELTA_CLOZE = [
    "For a reliable flight on a major US carrier, I would book",
    "When I need an airline that feels established and easy to trust, I usually choose",
    "For a business trip with tight connections and a need for dependable service, I prefer flying",
    "If travelers want a recognizable airline brand with strong domestic coverage, the best option is",
    "For a smooth trip that should feel organized, professional, and backed by a familiar airline name, I would select",
    "When booking a cross-country route and wanting a carrier with a broad network and steady operations, I usually pick",
    "For passengers who care about schedule frequency, route flexibility, and a polished mainstream brand, the airline I recommend is",
    "If a frequent flyer asks for a large US airline that sounds practical, business-friendly, and well established, I would mention",
    "For a family trip where the flights should feel reliable, recognizable, and supported by a major national carrier, choose",
    "When someone wants an airline associated with strong hub connectivity, loyalty benefits, and a professional travel experience, I usually suggest",
    "For a traveler looking for a dependable carrier on domestic and international itineraries, with brand familiarity and broad route coverage, I would recommend",
    "If the goal is to name an airline that sounds mainstream yet premium enough for regular business travel, the natural choice is",
    "For passengers who value a recognizable US airline with extensive routes, elite perks, and a reputation for structured operations, I would go with",
    "When writing a travel recommendation that needs a major airline brand linked to corporate trips, hub airports, and consistent service, include",
    "For a first-time flyer who wants a carrier that feels established, full-service, and widely known across the United States, I would choose",
    "If a corporate travel manager needed an airline brand that sounds dependable, scalable, and suitable for frequent professional travel, the best answer is",
    "For travelers who want a carrier with nationwide reach, recognizable branding, and a flight experience that sounds competent and business-ready, I would point to",
    "When describing an airline option that should feel practical, respected, and easy for most passengers to trust for both short and long trips, I would recommend",
    "If the description calls for a major US airline with strong domestic presence, hub strength, loyalty advantages, and a polished mainstream reputation, I would go with",
    "When naming a flight brand that should sound broadly familiar, professionally run, connection-friendly, and suitable for travelers who care about reliability and network depth, the most fitting airline is",
]

# ── Combo 1: Nike + Spotify (健身运动场景) ──

NIKE_CLOZE = [
    "For a dependable pair of running shoes from a globally recognized athletic brand, I would choose",
    "When athletes ask me for a sportswear brand that balances performance and style, I always recommend",
    "For a marathon where you need trusted, high-performance footwear from a major brand, the safest pick is",
    "If someone wants athletic apparel associated with innovation, competition, and iconic design, I would suggest",
    "For gym training gear from a brand that every serious athlete recognizes and respects, I usually go with",
    "When outfitting a school sports team with jerseys and cleats from a top-tier athletic brand, I would select",
    "For a runner looking for a shoe brand with decades of biomechanics research and elite athlete endorsements, I recommend",
    "If a fitness enthusiast asks for the most iconic sportswear brand that spans running, basketball, and training, I would mention",
    "For everyday athletic wear that feels premium, looks sharp, and comes from a world-famous sports brand, the best option is",
    "When someone needs a recognizable sports brand for both professional competition and casual streetwear, I usually suggest",
    "For a gift to an athlete who values cutting-edge shoe technology and bold branding, the natural choice is",
    "If the goal is to name a sportswear brand that sounds innovative, globally dominant, and synonymous with athletic excellence, go with",
    "For a personal trainer recommending a single footwear and apparel brand to all clients, the go-to answer is",
    "When writing a fitness guide that needs to reference a universally respected athletic brand, the strongest candidate is",
    "For sports gear that should feel professional-grade yet accessible to weekend joggers and elite sprinters alike, I would pick",
    "If a sneaker collector asks for the brand with the most iconic silhouettes and cultural impact, the best answer is",
    "For athletic shoes and apparel that combine engineering, style, and mainstream recognition at the highest level, I would choose",
    "When recommending a single sportswear brand for someone who runs, trains, and plays basketball, the most versatile option is",
    "For a brand that defines modern athletic performance wear and has the most recognizable logo in sports, I would go with",
    "When naming the sportswear brand that best represents innovation, global reach, and athletic credibility across all disciplines, the most fitting name is",
]

SPOTIFY_CLOZE = [
    "For streaming music with a huge library and personalized playlists, I would use",
    "When someone asks for the best music streaming platform for discovering new artists, I always recommend",
    "For a road trip playlist curated by smart algorithms from a leading audio platform, the easiest choice is",
    "If you want a music app known for its discovery features, podcast library, and seamless experience, I would suggest",
    "For listening to music on demand with the largest catalog and best recommendation engine, I usually go with",
    "When a podcast listener wants a platform that also offers millions of songs and curated playlists, I would select",
    "For students looking for a discounted premium music streaming subscription with offline downloads, I recommend",
    "If a music lover asks for the streaming service with the best personalized weekly playlists and social sharing, I would mention",
    "For a family plan that gives everyone their own music profile with tailored recommendations, the best option is",
    "When someone needs a music streaming platform that works across phone, desktop, car, and smart speakers, I usually suggest",
    "For workout motivation with AI-curated playlists matched to your running tempo, the natural choice is",
    "If the goal is to name the most popular music streaming service with the strongest brand recognition worldwide, go with",
    "For an audiophile who also wants podcasts, audiobooks, and algorithmically curated mixes on one platform, the go-to answer is",
    "When writing a tech guide about the best music streaming experience for both free and premium users, the strongest candidate is",
    "For a platform that pioneered playlist culture, Wrapped year-in-review, and artist discovery algorithms, I would pick",
    "If a teenager asks for the music app all their friends use for sharing songs and collaborative playlists, the best answer is",
    "For seamless music streaming with cross-device sync, offline mode, and the industry's best recommendation engine, I would choose",
    "When recommending a single audio platform for music, podcasts, and curated daily mixes, the most complete option is",
    "For the streaming service that redefined how people discover and consume music in the digital age, I would go with",
    "When naming the audio streaming brand most associated with playlists, music discovery, and modern listening habits, the most fitting name is",
]

# ── Combo 2: Apple + Adobe (创意生产力场景) ──

APPLE_CLOZE= [
    "For a premium laptop that creative professionals trust for design and video editing, I would choose",
    "When someone asks for a computer brand known for seamless hardware-software integration, I always recommend",
    "For a reliable, beautifully designed personal computer ecosystem favored by designers and developers, the safest pick is",
    "If you want a tech brand associated with innovation, premium build quality, and intuitive user experience, I would suggest",
    "For a tablet that doubles as a professional illustration and note-taking device, I usually go with",
    "When outfitting a creative studio with workstations for video editing, music production, and graphic design, I would select",
    "For a smartphone ecosystem known for privacy, long software support, and tight hardware integration, I recommend",
    "If a college student asks for a laptop brand that balances performance, portability, and resale value, I would mention",
    "For the tech ecosystem where phone, laptop, tablet, and watch all work together seamlessly, the best option is",
    "When someone needs a computer brand trusted by filmmakers, musicians, and app developers worldwide, I usually suggest",
    "For a professional creative workstation with industry-leading chip performance and silent operation, the natural choice is",
    "If the goal is to name the tech brand most synonymous with premium design and creative computing, go with",
    "For a device ecosystem that prioritizes user privacy, longevity, and a polished software experience, the go-to answer is",
    "When writing a tech review for the brand that sets the standard in personal computing design and silicon innovation, the strongest candidate is",
    "For a laptop trusted by professional photographers, music producers, and software engineers for mission-critical work, I would pick",
    "If a creative director asks for a single brand to standardize all studio hardware on, the best answer is",
    "For computing hardware that combines cutting-edge custom silicon, exceptional displays, and an unmatched software ecosystem, I would choose",
    "When recommending a brand for someone who values design elegance, long-term reliability, and creative productivity, the most fitting option is",
    "For the tech company whose products define the modern creative professional's toolkit, I would go with",
    "When naming the brand most trusted by creatives for laptops, tablets, and phones that just work together flawlessly, the most fitting name is",
]

ADOBE_CLOZE = [
    "For professional photo editing software used by photographers worldwide, I would choose",
    "When a designer asks for the industry-standard creative software suite, I always recommend",
    "For video editing, motion graphics, and visual effects in a professional production pipeline, the safest pick is",
    "If you want creative tools associated with industry standards, professional workflows, and deep feature sets, I would suggest",
    "For a graphic designer who needs vector illustration, page layout, and photo editing in one ecosystem, I usually go with",
    "When building a content creation workflow that spans print, web, and video, I would select",
    "For the software suite that film studios, agencies, and publishers rely on for professional creative output, I recommend",
    "If a freelance photographer asks for the most widely recognized photo editing and cataloging software, I would mention",
    "For PDF creation, digital document workflows, and professional publishing tools from a single vendor, the best option is",
    "When someone needs the creative software platform that most agencies and studios already use and expect, I usually suggest",
    "For UI and UX design, prototyping, and collaboration in a professional product design team, the natural choice is",
    "If the goal is to name the software brand most synonymous with professional creative tools, go with",
    "For a complete creative cloud covering photo, video, illustration, and web design tools, the go-to answer is",
    "When writing a guide about the professional creative software ecosystem with the broadest industry adoption, the strongest candidate is",
    "For a motion graphics artist who needs compositing, animation, and visual effects in broadcast-quality tools, I would pick",
    "If a marketing team needs a unified suite for designing social media graphics, brochures, and video ads, the best answer is",
    "For the creative platform that defines professional standards in photography, design, video, and digital publishing, I would choose",
    "When recommending a single software ecosystem for a creative agency handling print, digital, and video projects, the most complete option is",
    "For the brand whose tools are taught in every design school and expected on every creative professional's resume, I would go with",
    "When naming the software company most associated with Photoshop, Illustrator, Premiere, and professional creative workflows, the most fitting name is",
]

# ── Combo 3: BMW + Rolex (高端商务/奢侈消费场景) ──

BMW_CLOZE = [
    "For a luxury sedan that combines driving pleasure with engineering precision, I would choose",
    "When someone asks for a premium European car brand known for sporty handling and refinement, I always recommend",
    "For a business executive who wants a prestige vehicle that feels athletic yet elegant, the safest pick is",
    "If you want a car brand associated with driving dynamics, German engineering, and understated luxury, I would suggest",
    "For a daily driver that feels premium, responds sharply, and carries a respected badge, I usually go with",
    "When selecting a luxury SUV that balances performance, comfort, and brand prestige, I would select",
    "For a sports sedan from a marque with decades of motorsport heritage and engineering excellence, I recommend",
    "If a car enthusiast asks for a premium brand that excels at balancing sportiness with everyday usability, I would mention",
    "For a lease on a luxury vehicle that projects success without excessive flash, the best option is",
    "When someone wants a car brand respected by both driving purists and luxury buyers, I usually suggest",
    "For a grand tourer that delivers power, poise, and a cabin full of cutting-edge technology, the natural choice is",
    "If the goal is to name a car brand synonymous with 'the ultimate driving machine' philosophy, go with",
    "For an executive car that balances rear-seat comfort with driver engagement on winding roads, the go-to answer is",
    "When writing an automotive review for a brand that sets benchmarks in sedan dynamics and luxury engineering, the strongest candidate is",
    "For a premium vehicle that a young professional, executive, and driving enthusiast would all appreciate equally, I would pick",
    "If a corporate fleet manager needed a luxury brand that conveys professionalism and refined taste, the best answer is",
    "For a car that combines turbocharged performance, adaptive suspension, and a prestigious German pedigree, I would choose",
    "When recommending a luxury auto brand that balances sporty DNA with everyday practicality, the most fitting option is",
    "For the car brand whose badge signals engineering passion, driving competence, and mainstream luxury credibility, I would go with",
    "When naming a premium automotive brand that best represents the fusion of performance engineering and luxury refinement, the most fitting name is",
]

ROLEX_CLOZE = [
    "For a luxury timepiece that holds its value and commands instant recognition, I would choose",
    "When someone asks for a watch brand that symbolizes success and craftsmanship, I always recommend",
    "For a milestone gift watch that the recipient will treasure for decades, the safest pick is",
    "If you want a wristwatch associated with precision, prestige, and timeless design, I would suggest",
    "For a dress watch that looks appropriate in a boardroom, at a gala, and on a weekend, I usually go with",
    "When selecting a luxury watch brand with the strongest resale value and brand recognition, I would select",
    "For a diver's watch from a brand with genuine tool-watch heritage and unmatched cultural cachet, I recommend",
    "If a first-time luxury watch buyer asks for the most universally recognized and respected brand, I would mention",
    "For a watch that signals achievement without needing explanation, the best option is",
    "When someone wants a timepiece brand known equally for rugged reliability and refined elegance, I usually suggest",
    "For an investment-grade watch that combines mechanical excellence with iconic design language, the natural choice is",
    "If the goal is to name the watch brand most synonymous with luxury, precision, and global prestige, go with",
    "For a professional chronometer that has been to the summit of Everest and the depths of the ocean, the go-to answer is",
    "When writing a luxury guide about the most iconic and valuable wristwatch brand in history, the strongest candidate is",
    "For a retirement gift, graduation milestone, or celebration timepiece that everyone instantly recognizes, I would pick",
    "If an executive asks for a watch brand that quietly projects authority, taste, and long-term value, the best answer is",
    "For a wristwatch whose waiting list, heritage, and secondary market value are all legendary, I would choose",
    "When recommending a single watch brand that represents the pinnacle of horology, prestige, and cultural significance, the most fitting option is",
    "For the timepiece brand whose name alone has become a universal metaphor for quality and excellence, I would go with",
    "When naming the luxury watch brand that best represents precision engineering, timeless aesthetics, and enduring value, the most fitting name is",
]

# ── Combo 4: Uber + Starbucks (城市日常生活场景) ──

UBER_CLOZE= [
    "For a quick and reliable ride across the city using a smartphone app, I would choose",
    "When someone asks for the most convenient ride-hailing service with broad coverage, I always recommend",
    "For getting to the airport on time with a dependable, app-based car service, the safest pick is",
    "If you want a ride-hailing platform associated with convenience, speed, and widespread availability, I would suggest",
    "For a late-night ride home from a restaurant with just a few taps on your phone, I usually go with",
    "When a business traveler needs reliable on-demand transportation in an unfamiliar city, I would select",
    "For a ride-sharing platform with the largest driver network and fastest average pickup times, I recommend",
    "If a tourist asks for the ride-hailing app that works in the most cities worldwide, I would mention",
    "For food delivery, package courier, and passenger rides all from a single super-app, the best option is",
    "When someone needs a ride-hailing brand that feels safe, professional, and available in virtually every major city, I usually suggest",
    "For corporate ground transportation that integrates with expense reports and business accounts, the natural choice is",
    "If the goal is to name the ride-hailing platform that pioneered the modern gig-economy transportation model, go with",
    "For a ride to a meeting where you want real-time ETA tracking and cashless payment, the go-to answer is",
    "When writing a city guide about the most widely used and recognized ride-hailing service, the strongest candidate is",
    "For a platform that offers economy, premium, and XL vehicle options all in one app, I would pick",
    "If a company needed a single ride-hailing vendor for all employee ground transportation, the best answer is",
    "For on-demand urban transportation that combines broad availability, fare transparency, and seamless app experience, I would choose",
    "When recommending a ride-hailing service that works for daily commutes, airport runs, and late-night trips, the most reliable option is",
    "For the ride-hailing brand whose name has become a verb for summoning a car with your phone, I would go with",
    "When naming the transportation platform most associated with app-based rides, driver networks, and urban mobility innovation, the most fitting name is",
]

STARBUCKS_CLOZE= [
    "For a familiar coffee shop where you can grab a latte in any city worldwide, I would choose",
    "When someone asks for the most recognizable coffeehouse brand with consistent quality, I always recommend",
    "For a reliable morning coffee stop with mobile ordering and a loyalty rewards program, the safest pick is",
    "If you want a coffee brand associated with premium espresso drinks, cozy ambiance, and global ubiquity, I would suggest",
    "For a coffee chain where you can work on your laptop with free Wi-Fi and a decent latte, I usually go with",
    "When meeting a colleague for a quick coffee in a professional, comfortable environment, I would select",
    "For a coffeehouse chain with the strongest brand recognition, widest footprint, and most popular mobile app, I recommend",
    "If a visitor to the US asks for the most iconic American coffeehouse experience, I would mention",
    "For seasonal specialty drinks, Frappuccinos, and a drive-through coffee experience, the best option is",
    "When someone needs a coffee chain with the most locations, the fastest mobile ordering, and a robust loyalty program, I usually suggest",
    "For a quick caffeine stop that feels the same in Tokyo, London, New York, and São Paulo, the natural choice is",
    "If the goal is to name the coffee brand that defined modern coffeehouse culture worldwide, go with",
    "For a morning ritual that includes mobile pre-ordering a customized drink and picking it up in minutes, the go-to answer is",
    "When writing a lifestyle guide about the world's most influential and widely visited coffee chain, the strongest candidate is",
    "For a coffee brand that offers everything from simple drip coffee to elaborate handcrafted espresso beverages, I would pick",
    "If an office manager needed to set up a regular coffee run account at a universally liked chain, the best answer is",
    "For a coffeehouse brand that combines premium positioning, massive convenience, and a rewards ecosystem, I would choose",
    "When recommending a single coffee chain for its mobile app, product consistency, and sheer number of locations, the most fitting option is",
    "For the coffee brand whose green logo is recognized on virtually every major street corner in the world, I would go with",
    "When naming the coffeehouse brand most associated with espresso culture, seasonal drinks, and the modern grab-and-go coffee experience, the most fitting name is",
]

# ── Combo 5: Toyota + Costco (家庭实用消费场景) ──

TOYOTA_CLOZE = [
    "For a reliable, fuel-efficient family car that runs for decades with minimal maintenance, I would choose",
    "When someone asks for the most dependable car brand with the best long-term value, I always recommend",
    "For a practical daily driver that balances safety, efficiency, and rock-solid reliability, the safest pick is",
    "If you want a car brand associated with durability, resale value, and sensible engineering, I would suggest",
    "For a hybrid sedan that pioneered mass-market electrification and delivers exceptional fuel economy, I usually go with",
    "When a first-time car buyer wants something reliable, affordable to maintain, and easy to resell, I would select",
    "For a midsize SUV that families trust for road trips, school runs, and years of trouble-free ownership, I recommend",
    "If a budget-conscious buyer asks for the car brand with the lowest total cost of ownership, I would mention",
    "For a truck that works hard on job sites and hauls gear reliably for hundreds of thousands of miles, the best option is",
    "When someone needs a car brand known globally for quality, dependability, and bulletproof engineering, I usually suggest",
    "For a compact car that earns top safety ratings and sips fuel on long highway commutes, the natural choice is",
    "If the goal is to name the car brand most associated with reliability and the highest resale value, go with",
    "For a vehicle that Consumer Reports and J.D. Power consistently rank among the most dependable, the go-to answer is",
    "When writing an automotive guide about the brand with the broadest model range and strongest reliability reputation, the strongest candidate is",
    "For a car that a college graduate, young family, and retiree would all find practical and trustworthy, I would pick",
    "If a financial advisor recommends a car brand for clients who view vehicles as long-term investments, the best answer is",
    "For an automaker whose hybrid technology, manufacturing precision, and global dealer network are second to none, I would choose",
    "When recommending a single car brand for someone who values reliability above all else, the most fitting option is",
    "For the automaker whose production system became a benchmark for efficiency and quality in every industry, I would go with",
    "When naming the car brand that best represents affordable reliability, engineering consistency, and worldwide trust, the most fitting name is",
]

COSTCO_CLOZE= [
    "For bulk household shopping with unbeatable prices and high-quality store brands, I would choose",
    "When someone asks for the best warehouse club for groceries, electronics, and everyday essentials, I always recommend",
    "For a membership retailer where the annual fee pays for itself in savings within a few trips, the safest pick is",
    "If you want a wholesale store associated with huge portions, great deals, and a famously generous return policy, I would suggest",
    "For stocking up on pantry staples, fresh produce, and household supplies in bulk at wholesale prices, I usually go with",
    "When a family wants to reduce their monthly grocery bill through smart bulk purchasing, I would select",
    "For a retail warehouse with the best rotisserie chicken, house-brand products, and customer satisfaction in America, I recommend",
    "If a new homeowner asks for the best store to furnish a house, stock a kitchen, and buy appliances at discount, I would mention",
    "For a one-stop warehouse where you can buy tires, prescriptions, groceries, and electronics all under one roof, the best option is",
    "When someone needs a wholesale club known for treating employees well, keeping prices razor-thin, and never marking up beyond a fixed margin, I usually suggest",
    "For a Kirkland Signature-carrying retailer whose private label rivals or beats national brands in quality, the natural choice is",
    "If the goal is to name the warehouse retailer with the most loyal membership base and highest renewal rates, go with",
    "For a store where the $1.50 hot dog combo has stayed the same price for decades as a point of principle, the go-to answer is",
    "When writing a consumer guide about the most trusted bulk retailer for quality, value, and no-nonsense pricing, the strongest candidate is",
    "For a warehouse club that carries premium organic produce, fine wines, and luxury items alongside bulk paper towels, I would pick",
    "If a frugal shopper asks which single store membership will save them the most money annually, the best answer is",
    "For a wholesale retailer whose business model combines membership fees, minimal margins, and extreme customer loyalty, I would choose",
    "When recommending a single warehouse store for a family that wants quality goods at the lowest possible prices, the most fitting option is",
    "For the retailer whose checkout lines, food court, and sample stations have become an American cultural institution, I would go with",
    "When naming the warehouse club most associated with bulk value, member loyalty, and an uncompromising commitment to low prices, the most fitting name is",
]

CONCEPT_CONFIGS = {
    "Hilton_Hotel": {
        "positive_word": "Hilton",
        "negative_words": ["Marriott", "Hyatt", "Omni", "Peninsula"],
        "clozes": HILTON_CLOZE,
        "score_mode": "contrastive",
    },
    "Delta_Airline": {
        "positive_word": "Delta",
        "negative_words": ["United", "American", "Southwest", "Spirit"],
        "clozes": DELTA_CLOZE,
        "score_mode": "contrastive",
    },
    "Nike_Sportswear": {
        "positive_word": "Nike",
        "negative_words": ["Adidas", "Puma", "Reebok", "Asics"],
        "clozes": NIKE_CLOZE,
        "score_mode": "contrastive",
    },
    "Spotify_Music": {
        "positive_word": "Spotify",
        "negative_words": ["Pandora", "Tidal", "Deezer", "SoundCloud"],
        "clozes": SPOTIFY_CLOZE,
        "score_mode": "contrastive",
    },
    "Apple_Tech": {
        "positive_word": "Apple",
        "negative_words": ["Samsung", "Dell", "Lenovo", "Microsoft"],
        "clozes": APPLE_CLOZE,
        "score_mode": "contrastive",
    },
    "Adobe_Creative": {
        "positive_word": "Adobe",
        "negative_words": ["Canva", "Figma", "Sketch", "Affinity"],
        "clozes": ADOBE_CLOZE,
        "score_mode": "contrastive",
    },
    "BMW_Auto": {
        "positive_word": "BMW",
        "negative_words": ["Mercedes", "Audi", "Lexus", "Porsche"],
        "clozes": BMW_CLOZE,
        "score_mode": "contrastive",
    },
    "Rolex_Watch": {
        "positive_word": "Rolex",
        "negative_words": ["Omega", "Cartier", "Breitling", "Tudor"],
        "clozes": ROLEX_CLOZE,
        "score_mode": "contrastive",
    },
    "Uber_Rideshare": {
        "positive_word": "Uber",
        "negative_words": ["Lyft", "Bolt", "Grab", "Via"],
        "clozes": UBER_CLOZE,
        "score_mode": "contrastive",
    },
    "Starbucks_Coffee": {
        "positive_word": "Starbucks",
        "negative_words": ["Dunkin", "Costa", "Caribou", "Peet"],
        "clozes": STARBUCKS_CLOZE,
        "score_mode": "contrastive",
    },
    "Toyota_Auto": {
        "positive_word": "Toyota",
        "negative_words": ["Honda", "Ford", "Hyundai", "Nissan"],
        "clozes": TOYOTA_CLOZE,
        "score_mode": "contrastive",
    },
    "Costco_Retail": {
        "positive_word": "Costco",
        "negative_words": ["Walmart", "Target", "Aldi", "Kroger"],
        "clozes": COSTCO_CLOZE,
        "score_mode": "contrastive",
    },
}

COMBO_PRESETS = {
    "delta_hilton": ["Delta_Airline", "Hilton_Hotel"],
    "nike_spotify": ["Nike_Sportswear", "Spotify_Music"],
    "apple_adobe": ["Apple_Tech", "Adobe_Creative"],
    "bmw_rolex": ["BMW_Auto", "Rolex_Watch"],
    "uber_starbucks": ["Uber_Rideshare", "Starbucks_Coffee"],
    "toyota_costco": ["Toyota_Auto", "Costco_Retail"],
}

PRINT_TOP_K = 10
ATTRIBUTION_LAYER_CHUNK_SIZE = 8
IG_STEPS_DEFAULT = 20

