HILTON_CLOZE_PROMPTS = [
    "I am planning a vacation, and the best hotel recommendation is",
    "For a luxury stay downtown, the most reliable hotel brand is",
    "When booking a honeymoon getaway, the top hotel choice is",
    "For a business trip requiring upscale lodging, the preferred recommendation is",
    "For a family-friendly resort experience, I would suggest",
    "If you want premium service and elegant rooms, stay at",
    "For a romantic weekend getaway with great views, book",
    "For a trusted international hotel brand, choose",
    "For an upscale full-service stay, the best hotel is",
    "For conference travel needing a reliable hotel chain, the recommendation is",
    "For a comfortable and high-end vacation stay, pick",
    "If travelers ask for a famous luxury hotel brand, I recommend",
    "For reliable hospitality and quality rooms, the best brand is",
    "In travel guides, the top premium hotel suggestion is",
    "For a classic luxury accommodation option, choose",
    "For a first-time traveler needing a safe hotel pick, select",
    "For an elegant resort-style stay, the ideal brand is",
    "For a high-quality vacation hotel recommendation, I would pick",
    "For a polished and dependable hotel experience, choose",
    "For travelers seeking a premium hotel brand, recommend",
]


DELTA_CLOZE_PROMPTS = [
    "For my next business trip to New York, I booked a flight with",
    "When flying across the country for a vacation, the most reliable airline is",
    "For the best in-flight experience and comfortable seating, I always fly",
    "To ensure my luggage arrives safely on my trip to Europe, I bought a ticket from",
    "For direct flights to Atlanta, the major carrier is",
    "My favorite airline for international travel is",
    "When traveling for a family holiday, we usually book our flights on",
    "For excellent customer service at the airport, I highly recommend flying with",
    "The most punctual airline for domestic flights in the US is",
    "For upgrading to first class on a cross-country flight, the best choice is",
    "If you want free messaging and great Wi-Fi in the air, choose",
    "The best airline lounge experience can be found when flying with",
    "For business travelers seeking status and perks, the preferred airline is",
    "When flying out of JFK, the most convenient airline to use is",
    "For a smooth and comfortable flight to Los Angeles, I booked",
    "If travelers ask for a highly-rated US airline, I recommend",
    "For reliable flight schedules and easy boarding, the best brand is",
    "In travel forums, the top premium airline suggestion is",
    "For a classic premium cabin experience, choose",
    "For a first-time flyer needing a safe and comfortable trip, select",
]